// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCZz_3fxb1asmwG1gLldyy_A_e9MJaFZ8',
    appId: '1:910483869279:web:b38e84627f6d6f8bba95ea',
    messagingSenderId: '910483869279',
    projectId: 'ai-language-learning-app-49636',
    authDomain: 'ai-language-learning-app-49636.firebaseapp.com',
    storageBucket: 'ai-language-learning-app-49636.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPL0hb4DDt6HZWbTfTALhU5_PhvJUcEWI',
    appId: '1:910483869279:android:22305cf6cf2b781cba95ea',
    messagingSenderId: '910483869279',
    projectId: 'ai-language-learning-app-49636',
    storageBucket: 'ai-language-learning-app-49636.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUEMTemkXeKfHsP7tDZ2P6PNFEdKXf8ck',
    appId: '1:910483869279:ios:2e652e90de54cf61ba95ea',
    messagingSenderId: '910483869279',
    projectId: 'ai-language-learning-app-49636',
    storageBucket: 'ai-language-learning-app-49636.firebasestorage.app',
    iosBundleId: 'com.example.aiLanguageLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUEMTemkXeKfHsP7tDZ2P6PNFEdKXf8ck',
    appId: '1:910483869279:ios:2e652e90de54cf61ba95ea',
    messagingSenderId: '910483869279',
    projectId: 'ai-language-learning-app-49636',
    storageBucket: 'ai-language-learning-app-49636.firebasestorage.app',
    iosBundleId: 'com.example.aiLanguageLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCZz_3fxb1asmwG1gLldyy_A_e9MJaFZ8',
    appId: '1:910483869279:web:6734bc5855ad9bdaba95ea',
    messagingSenderId: '910483869279',
    projectId: 'ai-language-learning-app-49636',
    authDomain: 'ai-language-learning-app-49636.firebaseapp.com',
    storageBucket: 'ai-language-learning-app-49636.firebasestorage.app',
  );
}
